import React, { Fragment } from 'react';
import { Counter } from '../features/Counter/components/Counter';

export const Home: React.FC = () => (
  <Fragment>
    <h1>Home Page</h1>
    <Counter />

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis tincidunt eros dui, sit amet venenatis quam mollis vel. Fusce at lorem nec velit ultrices hendrerit eu et dolor. Phasellus consequat tortor quis enim interdum, sit amet tristique ante tristique. Aenean vitae hendrerit purus. Ut ornare sed nisl ac blandit. Maecenas at egestas metus. Vestibulum pellentesque velit at elit volutpat, in ultricies ipsum condimentum. Vivamus iaculis tempus ante sed luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum gravida malesuada est, id ullamcorper dui facilisis sed. Phasellus faucibus est vel porttitor pellentesque. Aliquam varius elit augue, non lacinia ipsum cursus nec. Pellentesque vestibulum felis non aliquet suscipit.</p>
    <p>Ut ut arcu maximus, hendrerit tellus auctor, consectetur magna. Donec pellentesque tempus nunc, a volutpat magna dictum id. Donec porta eros non sodales fringilla. In eleifend, est in tincidunt tincidunt, dui tortor finibus lacus, bibendum suscipit elit libero a dolor. Maecenas ut nunc eu lacus sagittis placerat in vel dolor. Suspendisse rutrum mi eget tellus semper, congue congue ligula molestie. Cras eu tincidunt enim, nec feugiat tellus. Donec porttitor hendrerit posuere. Proin auctor euismod consequat. Donec hendrerit enim eu lacus sodales, non facilisis ex dapibus. Suspendisse interdum turpis velit, ac condimentum neque faucibus non. Sed suscipit odio sed massa aliquet scelerisque in quis risus.</p>
    <p>Phasellus tincidunt tristique tortor in venenatis. Nulla ullamcorper nunc quam, eget tincidunt dui consectetur sed. Etiam mollis facilisis cursus. Nullam dapibus lectus ut sodales porta. Nulla nec ligula eget leo facilisis semper scelerisque vel risus. Sed suscipit ex libero, in pretium dolor vulputate non. Morbi varius, diam vestibulum sollicitudin suscipit, orci sapien dapibus orci, et gravida ipsum metus eleifend erat. Morbi dignissim sapien a purus molestie rutrum. Proin ut viverra leo. Aliquam quis euismod augue. Fusce ex quam, aliquet sed ullamcorper vel, scelerisque vel libero. Mauris a purus blandit elit blandit finibus nec vitae magna.</p>
    <p>Pellentesque commodo, risus vel accumsan malesuada, nulla ligula ornare nisl, sed pharetra sem augue consectetur dui. In rhoncus sapien ex, eu semper sem volutpat id. Aenean velit mauris, ullamcorper nec mauris eget, viverra dapibus ante. Aenean gravida tortor in enim ullamcorper, nec bibendum massa consequat. Nam consequat, diam sed varius dictum, urna turpis eleifend elit, et interdum sapien velit ut lacus. Aliquam commodo lacus at consequat luctus. Maecenas dui orci, congue vitae tincidunt eu, porttitor ac velit. Etiam vel tortor tellus. Ut non mattis massa. Sed odio ipsum, sagittis nec eleifend in, placerat vel nisi. Curabitur consequat dolor nulla, vitae elementum enim convallis ut. Curabitur nulla nibh, vehicula a venenatis in, accumsan eu magna. Fusce sagittis neque a purus bibendum, sit amet laoreet velit porta. Vestibulum sodales laoreet turpis, sed finibus mi lobortis sodales.</p>
    <p>Cras finibus lacus nulla, et porta tortor pellentesque at. Suspendisse suscipit, leo at pretium congue, odio dui laoreet risus, at scelerisque felis dui sit amet erat. Morbi magna tellus, hendrerit id vulputate ac, mattis id felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus tempor varius neque, vel mollis lacus ullamcorper in. Cras faucibus tincidunt ipsum, id accumsan ante luctus fringilla. Nullam feugiat faucibus nisl ut faucibus. Fusce non eleifend ipsum, facilisis mattis diam. Proin dignissim tempus semper. Donec placerat nisl ac purus convallis, non pellentesque orci ultrices. </p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis tincidunt eros dui, sit amet venenatis quam mollis vel. Fusce at lorem nec velit ultrices hendrerit eu et dolor. Phasellus consequat tortor quis enim interdum, sit amet tristique ante tristique. Aenean vitae hendrerit purus. Ut ornare sed nisl ac blandit. Maecenas at egestas metus. Vestibulum pellentesque velit at elit volutpat, in ultricies ipsum condimentum. Vivamus iaculis tempus ante sed luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum gravida malesuada est, id ullamcorper dui facilisis sed. Phasellus faucibus est vel porttitor pellentesque. Aliquam varius elit augue, non lacinia ipsum cursus nec. Pellentesque vestibulum felis non aliquet suscipit.</p>
    <p>Ut ut arcu maximus, hendrerit tellus auctor, consectetur magna. Donec pellentesque tempus nunc, a volutpat magna dictum id. Donec porta eros non sodales fringilla. In eleifend, est in tincidunt tincidunt, dui tortor finibus lacus, bibendum suscipit elit libero a dolor. Maecenas ut nunc eu lacus sagittis placerat in vel dolor. Suspendisse rutrum mi eget tellus semper, congue congue ligula molestie. Cras eu tincidunt enim, nec feugiat tellus. Donec porttitor hendrerit posuere. Proin auctor euismod consequat. Donec hendrerit enim eu lacus sodales, non facilisis ex dapibus. Suspendisse interdum turpis velit, ac condimentum neque faucibus non. Sed suscipit odio sed massa aliquet scelerisque in quis risus.</p>
    <p>Phasellus tincidunt tristique tortor in venenatis. Nulla ullamcorper nunc quam, eget tincidunt dui consectetur sed. Etiam mollis facilisis cursus. Nullam dapibus lectus ut sodales porta. Nulla nec ligula eget leo facilisis semper scelerisque vel risus. Sed suscipit ex libero, in pretium dolor vulputate non. Morbi varius, diam vestibulum sollicitudin suscipit, orci sapien dapibus orci, et gravida ipsum metus eleifend erat. Morbi dignissim sapien a purus molestie rutrum. Proin ut viverra leo. Aliquam quis euismod augue. Fusce ex quam, aliquet sed ullamcorper vel, scelerisque vel libero. Mauris a purus blandit elit blandit finibus nec vitae magna.</p>
    <p>Pellentesque commodo, risus vel accumsan malesuada, nulla ligula ornare nisl, sed pharetra sem augue consectetur dui. In rhoncus sapien ex, eu semper sem volutpat id. Aenean velit mauris, ullamcorper nec mauris eget, viverra dapibus ante. Aenean gravida tortor in enim ullamcorper, nec bibendum massa consequat. Nam consequat, diam sed varius dictum, urna turpis eleifend elit, et interdum sapien velit ut lacus. Aliquam commodo lacus at consequat luctus. Maecenas dui orci, congue vitae tincidunt eu, porttitor ac velit. Etiam vel tortor tellus. Ut non mattis massa. Sed odio ipsum, sagittis nec eleifend in, placerat vel nisi. Curabitur consequat dolor nulla, vitae elementum enim convallis ut. Curabitur nulla nibh, vehicula a venenatis in, accumsan eu magna. Fusce sagittis neque a purus bibendum, sit amet laoreet velit porta. Vestibulum sodales laoreet turpis, sed finibus mi lobortis sodales.</p>
    <p>Cras finibus lacus nulla, et porta tortor pellentesque at. Suspendisse suscipit, leo at pretium congue, odio dui laoreet risus, at scelerisque felis dui sit amet erat. Morbi magna tellus, hendrerit id vulputate ac, mattis id felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus tempor varius neque, vel mollis lacus ullamcorper in. Cras faucibus tincidunt ipsum, id accumsan ante luctus fringilla. Nullam feugiat faucibus nisl ut faucibus. Fusce non eleifend ipsum, facilisis mattis diam. Proin dignissim tempus semper. Donec placerat nisl ac purus convallis, non pellentesque orci ultrices. </p>
  </Fragment>
);
